[tool.poetry]
name = "day-18"
version = "0.1.0"
description = ""
authors = ["Jon Austin <jaustin@grubhub.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
